CREATE TABLE tab_inodes (inode BIGINT PRIMARY KEY, size BIGINT NOT NULL, hash BLOB(32) NULL, mtime DATETIME NULL, last_check DATETIME NULL, ack BOOLEAN);
CREATE TABLE tab_dentries (dnode BIGINT PRIMARY KEY NOT NULL, name VARCHAR(255) PRIMARY KEY NOT NULL, inode BIGINT NOT NULL, ack BOOLEAN);
