// generated by ./ddl2cpp tables.sql tbl_volume storage
#ifndef STORAGE_TBL_VOLUME_H
#define STORAGE_TBL_VOLUME_H

#include <sqlpp11/sqlpp11.h>
#include <sqlpp11/ppgen.h>

SQLPP_DECLARE_TABLE(
			(tab_volumes,\
			 SQLPP_CREATE_IF_NOT_EXISTS, \
			 SQLPP_CHARACTER_SET("utf-8") \
			 )
			,
			(id     , int		, SQLPP_PRIMARY_KEY, SQLPP_AUTO_INCREMENT)
			(uuid   , varchar(40)	, SQLPP_NOT_NULL)   
			(label	, varchar(32)	, SQLPP_NOT_NULL)   
			(mount	, text)   
			/*(last_check	, datetime)   */
)

#endif
