// generated by ./ddl2cpp tables.sql tbl_volume storage
#ifndef STORAGE_TBL_FILES_H
#define STORAGE_TBL_FILES_H

#include <sqlpp11/sqlpp11.h>
#include <chrono>

#include "sql_files.h"
using namespace tbls;

#if 0
#include <sqlpp11/ppgen.h>
using blob = sqlpp::blob;
using time_point = std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds>;

SQLPP_DECLARE_TABLE(
		(tab_inodes,\
		 SQLPP_CREATE_IF_NOT_EXISTS, \
		 SQLPP_CHARACTER_SET("utf-8") \
		 )
		,
		(inode  , bigint			, SQLPP_PRIMARY_KEY, SQLPP_NOT_NULL)
		(size	, bigint			, SQLPP_NOT_NULL)   
		(hash	, blob		, SQLPP_NULL)   
		(mtime	, time_point, SQLPP_NOT_NULL)
		(last_check	, time_point, SQLPP_NULL)
		(ack	, bool		, SQLPP_NOT_NULL)
)

#if 0
SQLPP_DECLARE_TABLE(
		(tab_dentries,\
		 SQLPP_CREATE_IF_NOT_EXISTS, \
		 SQLPP_CHARACTER_SET("utf-8") \
		 )
		,
		(dnode  , sqlpp::bigint			, SQLPP_PRIMARY_KEY, SQLPP_NOT_NULL)
		(name   , sqlpp::varchar		, SQLPP_PRIMARY_KEY, SQLPP_NOT_NULL)
		(inode  , sqlpp::bigint			, SQLPP_NOT_NULL)
		(ack	, sqlpp::boolean		, SQLPP_NOT_NULL)
)
#endif
#endif

#endif
